name: simple_shopping
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  json_annotation: ^4.8.1
  http: ^1.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_rating_stars: ^1.0.3+4
  flutter_native_splash: ^2.3.7

flutter_native_splash:
  android: true
  ios: true
  web: true
  fullscreen: true
  color_android: "#42a5f5"
  color: "#9CC0F5"

  android_12:
    color: "#9CC0F5"
    icon_background_color:  "#9CC0F5"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/facebook-logo-2019.png
    - assets/LogoGoogleTransparente.png
    - assets/LogoMarca.png

